# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72b95bc037ba6b1a3a8cf947ace69328"
name = "Bundle Box - Product Bundles"
application_url = "https://bundlebox-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_metaobjects,read_products,write_discounts,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://bundlebox-production.up.railway.app/api/auth" ]
